import type { Metadata } from "next";
import HeaderComponent from './_components/header'
import "./globals.css";

export const metadata: Metadata = {
 title: {
    default: "Create Next App",
    template:"%s | Shubham Tech"
  },
  description: "Generated by create next app",
};


export default async function RootLayout({children}){
console.log(await children.props);

  return (
    <html
      lang="en">

      <body className="min-h-full flex flex-col">
        {<HeaderComponent/>}
        {children}
        
        </body>
    </html>
  )
}
