import type { Metadata } from "next";
import Header from './_componensts/Header'
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const value=Math.random()
  // if(value>0.5){
  //   throw Error("Somthing went Wrong Globally")
  // }

  return (
    <html
      lang="en"
      className={''}
    >
      <body className="flex flex-col min-h-full">
        <Header/>
        {children}
        
        </body>
    </html>
  );
}
