import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: "Shubham Tech",
  description: "Generated by Shubham Yadav",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={``}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
