import Script from "next/script";
import type { Metadata } from "next";
import "./globals.css";
import ThemeChanger from './_components/ThemeChanger'
import ThemeButton from './_components/ThemeButton'

export const metadata: Metadata = {
  title: "Shubham tech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      lang="en" suppressHydrationWarning
    >
       
      <body className="flex flex-col min-h-full text-black dark:text-white dark:bg-black bg-amber-100">
       
      <ThemeChanger>
         <ThemeButton/>
        {children}
       </ThemeChanger>
        </body>
    </html>
  );
}
